version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=jdbc:postgresql://database:5432/ponto_eletronico
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    image: postgres:14
    environment:
      POSTGRES_DB: ponto_eletronico
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
